// Code generated by scripts/generate-controlplane-sdk.mjs; DO NOT EDIT.

package controlplane

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strings"
)

func (c *Client) EnsureTenant(ctx context.Context, req EnsureTenantRequest) (*TenantControlPlaneResponse, error) {
	return doJSON[EnsureTenantRequest, TenantControlPlaneResponse](ctx, c, http.MethodPost, "/api/internal/tenants/ensure", req, nil)
}

func (c *Client) GetTenantStatus(ctx context.Context, req TenantStatusRequest) (*TenantControlPlaneResponse, error) {
	params := url.Values{}
	params.Set("externalSource", strings.TrimSpace(req.ExternalSource))
	params.Set("externalSubjectType", strings.TrimSpace(req.ExternalSubjectType))
	params.Set("externalSubjectId", strings.TrimSpace(req.ExternalSubjectID))
	return doJSON[struct{}, TenantControlPlaneResponse](ctx, c, http.MethodGet, "/api/internal/tenants/status", struct{}{}, params)
}

func (c *Client) EnsureServiceAccount(ctx context.Context, req EnsureServiceAccountRequest) (*ServiceAccountControlPlaneResponse, error) {
	return doJSON[EnsureServiceAccountRequest, ServiceAccountControlPlaneResponse](ctx, c, http.MethodPost, "/api/internal/service-accounts/ensure", req, nil)
}

func (c *Client) SyncServiceAccountProfile(ctx context.Context, serviceAccountID string, req SyncServiceAccountProfileRequest) (*ServiceAccountControlPlaneResponse, error) {
	return doJSON[SyncServiceAccountProfileRequest, ServiceAccountControlPlaneResponse](ctx, c, http.MethodPost, fmt.Sprintf("/api/internal/service-accounts/%s/profile/sync", url.PathEscape(strings.TrimSpace(serviceAccountID))), req, nil)
}

func (c *Client) IssueServiceAccountRuntimeCredential(ctx context.Context, serviceAccountID string, req IssueServiceAccountRuntimeCredentialRequest) (*ServiceAccountRuntimeCredentialResponse, error) {
	return doJSON[IssueServiceAccountRuntimeCredentialRequest, ServiceAccountRuntimeCredentialResponse](ctx, c, http.MethodPost, fmt.Sprintf("/api/internal/service-accounts/%s/runtime-credential", url.PathEscape(strings.TrimSpace(serviceAccountID))), req, nil)
}

func (c *Client) IssueRuntimeSession(ctx context.Context, req IssueRuntimeSessionRequest) (*RuntimeSessionResponse, error) {
	return doJSON[IssueRuntimeSessionRequest, RuntimeSessionResponse](ctx, c, http.MethodPost, "/api/internal/runtime-sessions/issue", req, nil)
}

func (c *Client) EnsureTenantUser(ctx context.Context, req EnsureTenantUserRequest) (*TenantUserControlPlaneResponse, error) {
	return doJSON[EnsureTenantUserRequest, TenantUserControlPlaneResponse](ctx, c, http.MethodPost, "/api/internal/tenant-users/ensure", req, nil)
}

func (c *Client) ListTenantDepartments(ctx context.Context, arcubaseTenantID string) (*ListTenantDepartmentsResponse, error) {
	return doJSON[struct{}, ListTenantDepartmentsResponse](ctx, c, http.MethodGet, fmt.Sprintf("/api/internal/tenants/%s/departments/tree", url.PathEscape(strings.TrimSpace(arcubaseTenantID))), struct{}{}, nil)
}

func (c *Client) GetTenantDepartmentPaths(ctx context.Context, req GetTenantDepartmentPathsRequest) (*GetTenantDepartmentPathsResponse, error) {
	return doJSON[GetTenantDepartmentPathsRequest, GetTenantDepartmentPathsResponse](ctx, c, http.MethodPost, fmt.Sprintf("/api/internal/tenants/%s/departments/paths", url.PathEscape(strings.TrimSpace(req.ArcubaseTenantID))), req, nil)
}

func (c *Client) CreateTenantDepartment(ctx context.Context, arcubaseTenantID string, req CreateTenantDepartmentRequest) (*TenantDepartmentItem, error) {
	return doJSON[CreateTenantDepartmentRequest, TenantDepartmentItem](ctx, c, http.MethodPost, fmt.Sprintf("/api/internal/tenants/%s/departments", url.PathEscape(strings.TrimSpace(arcubaseTenantID))), req, nil)
}

func (c *Client) RenameTenantDepartment(ctx context.Context, arcubaseTenantID, departmentID string, req RenameTenantDepartmentRequest) (*TenantDepartmentItem, error) {
	return doJSON[RenameTenantDepartmentRequest, TenantDepartmentItem](ctx, c, http.MethodPut, fmt.Sprintf("/api/internal/tenants/%s/departments/%s/rename", url.PathEscape(strings.TrimSpace(arcubaseTenantID)), url.PathEscape(strings.TrimSpace(departmentID))), req, nil)
}

func (c *Client) DeleteTenantDepartment(ctx context.Context, arcubaseTenantID, departmentID string) error {
	_, err := doJSON[struct{}, bool](ctx, c, http.MethodDelete, fmt.Sprintf("/api/internal/tenants/%s/departments/%s", url.PathEscape(strings.TrimSpace(arcubaseTenantID)), url.PathEscape(strings.TrimSpace(departmentID))), struct{}{}, nil)
	return err
}

func (c *Client) RelocateTenantDepartment(ctx context.Context, arcubaseTenantID, departmentID string, req RelocateTenantDepartmentRequest) (*TenantDepartmentItem, error) {
	return doJSON[RelocateTenantDepartmentRequest, TenantDepartmentItem](ctx, c, http.MethodPut, fmt.Sprintf("/api/internal/tenants/%s/departments/%s/relocate", url.PathEscape(strings.TrimSpace(arcubaseTenantID)), url.PathEscape(strings.TrimSpace(departmentID))), req, nil)
}

func (c *Client) GetTenantUserDepartments(ctx context.Context, tenantUserID string, arcubaseTenantID string) (*TenantUserDepartmentsResponse, error) {
	params := url.Values{}
	params.Set("arcubaseTenantId", strings.TrimSpace(arcubaseTenantID))
	return doJSON[struct{}, TenantUserDepartmentsResponse](ctx, c, http.MethodGet, fmt.Sprintf("/api/internal/tenant-users/%s/departments", url.PathEscape(strings.TrimSpace(tenantUserID))), struct{}{}, params)
}

func (c *Client) UpdateTenantUserDepartments(ctx context.Context, tenantUserID string, req UpdateTenantUserDepartmentsRequest) (*TenantUserDepartmentsResponse, error) {
	return doJSON[UpdateTenantUserDepartmentsRequest, TenantUserDepartmentsResponse](ctx, c, http.MethodPut, fmt.Sprintf("/api/internal/tenant-users/%s/departments", url.PathEscape(strings.TrimSpace(tenantUserID))), req, nil)
}
