// Code generated by scripts/generate-controlplane-sdk.mjs; DO NOT EDIT.

package controlplane

import "time"

type TenantStatusRequest struct {
	ExternalSource      string `json:"externalSource" form:"externalSource"`
	ExternalSubjectType string `json:"externalSubjectType" form:"externalSubjectType"`
	ExternalSubjectID   string `json:"externalSubjectId" form:"externalSubjectId"`
}

type CreateTenantDepartmentRequest struct {
	Name     string `json:"name"`
	ParentID string `json:"parentId"`
}

type EnsureServiceAccountRequest struct {
	ArcubaseTenantID    string `json:"arcubaseTenantId"`
	AvatarURL           string `json:"avatarUrl"`
	Bio                 string `json:"bio"`
	DisplayName         string `json:"displayName"`
	ExternalSource      string `json:"externalSource"`
	ExternalSubjectID   string `json:"externalSubjectId"`
	ExternalSubjectType string `json:"externalSubjectType"`
	IdempotencyKey      string `json:"idempotencyKey"`
	IsAdmin             bool   `json:"isAdmin"`
}

type EnsureTenantRequest struct {
	DisplayName         string `json:"displayName"`
	ExternalSource      string `json:"externalSource"`
	ExternalSubjectID   string `json:"externalSubjectId"`
	ExternalSubjectType string `json:"externalSubjectType"`
	IdempotencyKey      string `json:"idempotencyKey"`
	SlugHint            string `json:"slugHint"`
}

type EnsureTenantUserRequest struct {
	ArcubaseTenantID    string `json:"arcubaseTenantId"`
	AvatarURL           string `json:"avatarUrl"`
	DisplayName         string `json:"displayName"`
	Email               string `json:"email"`
	ExternalSource      string `json:"externalSource"`
	ExternalSubjectID   string `json:"externalSubjectId"`
	ExternalSubjectType string `json:"externalSubjectType"`
	IdempotencyKey      string `json:"idempotencyKey"`
	IsAdmin             bool   `json:"isAdmin"`
	Mobile              string `json:"mobile"`
}

type GetTenantDepartmentPathsRequest struct {
	ArcubaseTenantID string   `json:"arcubaseTenantId"`
	DepartmentIDs    []string `json:"departmentIds"`
}

type GetTenantDepartmentPathsResponse struct {
	Paths [][]TenantDepartmentItem `json:"paths"`
}

type IssueRuntimeSessionRequest struct {
	ArcubaseTenantID string   `json:"arcubaseTenantId"`
	RequestedScope   []string `json:"requestedScope"`
	SubjectID        string   `json:"subjectId"`
	SubjectType      string   `json:"subjectType"`
}

type IssueServiceAccountRuntimeCredentialRequest struct {
	ArcubaseTenantID string   `json:"arcubaseTenantId"`
	RequestedScope   []string `json:"requestedScope"`
}

type ListTenantDepartmentsResponse struct {
	Items []TenantDepartmentItem `json:"items"`
}

type RelocateTenantDepartmentRequest struct {
	TargetID string `json:"targetId"`
	Type     string `json:"type"`
}

type RenameTenantOrganizationRoleRequest struct {
	Name string `json:"name"`
}

type RenameTenantDepartmentRequest struct {
	Name string `json:"name"`
}

type RuntimeSessionResponse struct {
	AccessToken    string    `json:"accessToken"`
	CredentialType string    `json:"credentialType"`
	ExpiresAt      time.Time `json:"expiresAt"`
	Scope          []string  `json:"scope"`
	SubjectID      string    `json:"subjectId"`
	SubjectType    string    `json:"subjectType"`
	TenantUserID   string    `json:"tenantUserId"`
}

type ServiceAccountControlPlaneResponse struct {
	ArcubaseTenantID            string     `json:"arcubaseTenantId"`
	AvatarURL                   string     `json:"avatarUrl"`
	Bio                         string     `json:"bio"`
	Created                     bool       `json:"created"`
	DisplayName                 string     `json:"displayName"`
	ExternalSource              string     `json:"externalSource"`
	ExternalSubjectID           string     `json:"externalSubjectId"`
	ExternalSubjectType         string     `json:"externalSubjectType"`
	ProfileSynced               bool       `json:"profileSynced"`
	ProfileSyncedAt             *time.Time `json:"profileSyncedAt"`
	ServiceAccountBindingStatus string     `json:"serviceAccountBindingStatus"`
	ServiceAccountID            string     `json:"serviceAccountId"`
	TenantUserID                string     `json:"tenantUserId"`
}

type ServiceAccountRuntimeCredentialResponse struct {
	AccessToken    string    `json:"accessToken"`
	CredentialType string    `json:"credentialType"`
	ExpiresAt      time.Time `json:"expiresAt"`
	Scope          []string  `json:"scope"`
	SubjectID      string    `json:"subjectId"`
	SubjectType    string    `json:"subjectType"`
	TenantUserID   string    `json:"tenantUserId"`
}

type TenantControlPlaneResponse struct {
	ArcubaseInstanceID  string `json:"arcubaseInstanceId"`
	ArcubaseTenantID    string `json:"arcubaseTenantId"`
	ArcubaseTenantSlug  string `json:"arcubaseTenantSlug"`
	Created             bool   `json:"created"`
	TenantBindingStatus string `json:"tenantBindingStatus"`
	TenantReady         bool   `json:"tenantReady"`
}

type TenantDepartmentItem struct {
	ChildDeptCount int                    `json:"childDeptCount"`
	Children       []TenantDepartmentItem `json:"children"`
	Depth          int                    `json:"depth"`
	ID             string                 `json:"id"`
	Name           string                 `json:"name"`
	ParentID       string                 `json:"parentId"`
	Path           string                 `json:"path"`
}

type TenantOrganizationRole struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type TenantUserControlPlaneResponse struct {
	ArcubaseTenantID    string `json:"arcubaseTenantId"`
	BindingStatus       string `json:"bindingStatus"`
	Created             bool   `json:"created"`
	DisplayName         string `json:"displayName"`
	Email               string `json:"email"`
	ExternalSource      string `json:"externalSource"`
	ExternalSubjectID   string `json:"externalSubjectId"`
	ExternalSubjectType string `json:"externalSubjectType"`
	IsAdmin             bool   `json:"isAdmin"`
	Mobile              string `json:"mobile"`
	TenantUserID        string `json:"tenantUserId"`
}

type TenantUserDepartmentsResponse struct {
	ArcubaseTenantID string   `json:"arcubaseTenantId"`
	DepartmentIDs    []string `json:"departmentIds"`
	TenantUserID     string   `json:"tenantUserId"`
}

type UpdateTenantUserDepartmentsRequest struct {
	ArcubaseTenantID string   `json:"arcubaseTenantId"`
	DepartmentIDs    []string `json:"departmentIds"`
}

type DisableTenantUserRequest struct {
	ArcubaseTenantID string `json:"arcubaseTenantId"`
}

type DisableTenantUserResponse struct {
	ArcubaseTenantID string `json:"arcubaseTenantId"`
	Disabled         bool   `json:"disabled"`
	TenantUserID     string `json:"tenantUserId"`
}
